export const SURVEYS_ACTION = Object.freeze({
  ADD_SURVEY_METADATA: 'ADD_SURVEY_METADATA',
  CHANGE_SURVEYS_METADATA: 'CHANGE_SURVEYS_METADATA',
  ADD_SURVEY_TO_CACHE: 'ADD_SURVEY_TO_CACHE',
  CHANGE_SURVEY: 'CHANGE_SURVEY',
});

export const LOGIN_ACTION = Object.freeze({});
